version: '3'

volumes:
  mongo_db : {}
services:
  node-app :
    build: .
    container_name: node-app
    environment:
      - PORT=4000
      - MONGO_IP=mongo
      - MONGO_PORT=27017
      - MONGO_USER=danny101201
      - MONGO_PASSWORD=Kjhg2365987
      # run mongo server first then run node server
    depends_on:
      - mongo
    ports:
      - 4000:4000
  mongo:
    image: mongo:4.4.3-bionic
    restart: always
    volumes:
      - mongo_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: danny101201
      MONGO_INITDB_ROOT_PASSWORD: Kjhg2365987
  
  