version: '3'

volumes: 
  node_volumn: {} 

services:
  nginx :
    ports :
    - 3000:80
  node-app :
    build : 
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ${PWD}:/app
      - node_volumn:/app/node_modules
    environment :
      - NODE_ENV=development
      - MONGO_USER=danny101201
      - MONGO_PASSWORD=Kjhg2365987
      - SESSION_SECRET=Danny 
    command : npm run dev
