version: '3'

services:
  nginx :
    ports :
    - 80:80
  node-app :
    build : 
      context: .
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis-12158.c299.asia-northeast1-1.gce.cloud.redislabs.com
      - REDIS_PORT=12158
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET} 
    command : node app.js
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}