version: '3'

volumes:
  mongo_db : {}
services:
  nginx :
    image: nginx
    volumes:
     - ${PWD}/nginx/default.conf:/etc/nginx/nginx.conf:ro
  node-app :
    build: .
    image: 0963802367/node-app
    container_name: node-app
    environment:
      - PORT=4000
      - SERVERBASEURL=/api/v1
      - MONGO_IP=mongo
      - MONGO_PORT=27017
      - MONGO_USER=danny101201
      - MONGO_PASSWORD=Kjhg2365987
      - SESSION_SECRET=Danny 
      # run mongo server first then run node server
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4.3-bionic
    restart: always
    volumes:
      - mongo_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: danny101201
      MONGO_INITDB_ROOT_PASSWORD: Kjhg2365987
  redis:
    image: redis
    ports:
      - 6379:6379

  
  